### ISSUE TITLE
The build fails for i386 CURRENT

### ISSUE THREAD

**Issue by arrowd** [hlh-restart/rtsx#8]
From packages building cluster log:

```
cc  -O2 -pipe -fno-strict-aliasing  -Werror -D_KERNEL -DKLD_MODULE -nostdinc   -include /wrkdirs/usr/ports/sysutils/rtsx-kmod/work/rtsx-2020-06-11/opt_global.h -I. -I/usr/src/sys -I/usr/src/sys/contrib/ck/include -fno-common  -fdebug-prefix-map=./machine=/usr/src/sys/i386/include -fdebug-prefix-map=./x86=/usr/src/sys/x86/include     -MD  -MF.depend.rtsx.o -MTrtsx.o -mno-mmx -mno-sse -msoft-float -ffreestanding -fwrapv -fstack-protector -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error-tautological-compare -Wno-error-empty-body -Wno-error-parentheses-equality -Wno-error-unused-function -Wno-error-pointer-sign -Wno-error-shift-negative-value -Wno-address-of-packed-member -Wno-format-zero-length   -mno-aes -mno-avx  -std=iso9899:1999 -c rtsx.c -o rtsx.o
rtsx.c:1475:10: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len, cmd->data->xfer_len);
                              ^~~~~~~~~~~~~~
rtsx.c:1475:26: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len, cmd->data->xfer_len);
                                              ^~~~~~~~~~~~~~~~~~~
rtsx.c:1479:10: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len);
                              ^~~~~~~~~~~~~~
rtsx.c:1669:10: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len, cmd->data->xfer_len);
                              ^~~~~~~~~~~~~~
rtsx.c:1669:26: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len, cmd->data->xfer_len);
                                              ^~~~~~~~~~~~~~~~~~~
rtsx.c:1673:10: error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                              cmd->data->len, RTSX_DMA_DATA_BUFSIZE);
                              ^~~~~~~~~~~~~~
6 errors generated.
```

Full log: http://beefy17.nyi.freebsd.org/data/head-i386-default/p538633_s362138/logs/rtsx-2020.06.11.log

**Comment by hlh-restart** [comment]
current master has been corrected to allow compilation on i386.
I will create a new tag when some test for RTS5227 are done.

**Comment by hlh-restart** [comment]
Have been solved with tag 2020-06-16

**Comment by arrowd** [comment]
Updated the port, thanks.

**Comment by arrowd** [comment]
Unfortunately, it still fails, now with different error: http://beefy10.nyi.freebsd.org/data/113i386-default/539306/logs/rtsx-2020.06.11.log

**Comment by hlh-restart** [comment]
I test on i386 under Freebsd 12.1-STABLE.
I will check.

**Comment by arrowd** [comment]
Ouch, sorry for the noise. It is leftovers from previous fallout, and the port version says 2020.06.11
